---
- name: NetBox Connection Test
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Hello AWX and Netbox
      debug:
        msg: "Hello World AWX and Netbox are powerful together!"

    - name: Display a Greeting from NetBox
      debug:
        msg: "Hello World! Ansible found device '{{ inventory_hostname }}' in NetBox."

    - name: Show Device Details
      debug:
        msg: "This device is at IP {{ ansible_host }} and has status {{ status.label }}."


















